### ISSUE TITLE
Generated Files

### ISSUE THREAD

**Issue by zpolygon95** [tmunro/remember-file-positions#6]
This package does not seem to work when generating and regenerating output files (from a command line program, etc.). I edit my source files, run the program (which I believe overwrites the file), and atom detects the change and reloads the updated file: the cursor is placed at the beginning of the output file.

I would be happy to work on this problem, if you accept pull requests!

**Comment by tmunro** [comment]
Hmm, I’m not sure off hand why that would be a problem. Feel free to poke around, I’d be happy to merge a fix.

Cheers,
Tom

**Comment by zpolygon95** [comment]
Just to pinpoint the problem, I created a test file and did the following:

``` BASH
for i in `seq 1 30`; do echo $i; done > test.txt
# I open the file in Atom, and place the cursor at line 15
echo testing >> test.txt
# appending data to the file doesn't seem to affect the cursor position
for i in `seq 31 60`; do echo $i; done > test.txt
# overwriting the file causes the cursor to be placed at the top of the file
```

**Comment by zpolygon95** [comment]
This is an old issue now, but I think it has more to do with atom than this package specifically. My workflow now is just to close the file before I regenerate it, then open it again afterwards.
