### ISSUE TITLE
Position not restored if the file is opened via command line.

### ISSUE THREAD

**Issue by CodeMan99** [tmunro/remember-file-positions#7]
1. Have atom already open.
2. Open a file from the tree and move cursor.
3. Close file.
4. Do `atom relative/path/to/file` from your command line shell.
5. Opens with the cursor at the beginning of the file.

**Comment by tmunro** [comment]
If you open it from the command line, move the cursor, close and reopen from the command line what happens? I wonder if it's getting a different file Uri in those cases.

Thanks,
Tom

**Comment by CodeMan99** [comment]
Does not seem to be URI based... at least not on the path part. Maybe the protocol is different ("http://" vs "file://")?

If I reverse the process and open from the command line first, and then from tree second it works as expected.

Opening from the command line fails with both relative and absolute paths. Fails when opening from the command line twice in a row as well.
